spring.application.name=AI-Study
server.port=9876
spring.datasource.url=jdbc:postgresql://localhost:5433/ai_study
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true